services:
  - type: web
    name: metro-verification-api
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DISCORD_CLIENT_ID
        sync: false
      - key: DISCORD_CLIENT_SECRET
        sync: false
      - key: MONGODB_URI
        value: mongodb+srv://metro_admin:o2lxi4D92JMCItdp@cluster0.nwzjrth.mongodb.net/metro_db?retryWrites=true&w=majority
      - key: REDIRECT_URI
        value: https://metro-verification-api.onrender.com/api/discord/callback
